### ISSUE TITLE
Create bootstrap/material versions of demo screen

### ISSUE THREAD

**Issue by boriscosic** [trufla-technology/ngx-tru-forms#1]
**Update 1: I included different demos as part of github pages build process. Github does not have a default fallback to index.html on 404 and so we needed separate directories. This was easier accomplished with build. This is easier because we now don't have to complicate the development.** 

[Read CONTRIBUTING first.](https://github.com/trufla-technology/ngx-tru-forms/blob/material-support/CONTRIBUTING.md)

Currently the example screen features only a material demo of components. We'd like to have both Bootstrap 4 & Material module available on separate routes. At the moment, Angular does not support module loading at runtime, which is used by ngx-tru-forms for form framework.

1. ~Create `material` & `bootstrap4` routes to bring up related modules. Empty route should default to material~.
2. ~Each module should be on its own route and does not have to be lazy loaded.~
3. Add a dropdown next to Schema Samples, for Framework with options of Bootstrap 4 or Material. Each dropdown should go to its designated route in point 1.
4. ~Try not to duplicate code of each components in modules. Extend the common logic from a shared component that's currently in json-schema-examples. You cannot load tru-forms dynamically thru json-schema-examples and that's why we need two additional modules for the framework.~
5. Do not break the functionality in the schema. Some of it is tailored to specific schemas and it is needed to test.
6. Review inputs and outputs of json-form.component.ts and ensure README is up to date for latest changes.

The integrity of the demo is important, it is our public facing site and showcase. Ensure it is adequately tested in all modes.

**Comment by mmounirf** [comment]
@boriscosic I was struggling to create switchable modules configuration in runtime `JsonFormModule.forRoot(_FRAMEWORK)` but I couldn't get anywhere, do you want to make different routes ? You already strikeout this point #1.

**Comment by georgesamir21** [comment]
@boriscosic  
***README***
`import { JsonFormModule, JsonFormMaterialModule } from '@trufla/ngx-tru-forms';

@NgModule({
  imports: [
    JsonFormModule.forRoot(JsonFormMaterialModule)
  ]
})`
is not showing the form, while 
`import { JsonFormFieldsService, JsonFormMaterial, JsonFormMaterialModule, JsonFormModule } from '@trufla/ngx-tru-forms';
@NgModule({
  imports: [
    JsonFormMaterialModule,
    {
      ngModule: JsonFormModule,
      providers: [
        {
          provide: JsonFormFieldsService,
          useClass: JsonFormMaterial,
          multi: true
        }
      ]
    },
  ],
});`
is the one working

**Comment by georgesamir21** [comment]
No example for "multi step form" in the readme
