### ISSUE TITLE
Add ability to share & load shares from pastebin

### ISSUE THREAD

**Issue by boriscosic** [trufla-technology/ngx-tru-forms#2]
@mmounirf It would be really neat if we could share snippets of JSON schema. There is a lot of times I build a sample for review and then it's a copy and paste process.

We can leverage the [pastebin API](https://pastebin.com/api.php) and then we can point it back to github like,
`https://trufla-technology.github.io/ngx-tru-forms/?framework=material&paste=[pastebinid]`

What do you think about adding a button under Data called Share and it generates above url?

**Comment by georgesamir21** [comment]
@boriscosic you mean to save the `schema` the entered in pastebin??
or you mean he writes the schema on pastebin and using its id we can bring it here??
